on:
  push:
    tags: ["v*"]

name: release

jobs:

  kbld-publish:
    name: Release
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write  # undocumented OIDC support.
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: sigstore/cosign-installer@main
      - name: login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $(echo ${{ github.actor }} | awk '{print tolower($0)}') --password-stdin
      - name: install carvel
        run: curl -L https://carvel.dev/install.sh | bash
      - name: build and sign bundle
        run: |
          set -e -x
          export COSIGN_EXPERIMENTAL=1
          tag_name="${GITHUB_REF##*/}"
          imgpkg push -b "ghcr.io/dennisdenuto/test-carvel-package-repo:${tag_name}" -f .
          cosign sign -a git_sha=$GITHUB_SHA "ghcr.io/dennisdenuto/test-carvel-package-repo:${tag_name}"


          cat <<EOF | kbld -f - > pkgr.yaml
          ---
          apiVersion: packaging.carvel.dev/v1alpha1
          kind: PackageRepository
          metadata:
            name: test-carvel-package-repo
          spec:
            fetch:
              imgpkgBundle:
                image: ghcr.io/dennisdenuto/test-carvel-package-repo:${tag_name}
          EOF

          cat <<EOF | kbld -f - > pkgi.yaml
          ---
          apiVersion: packaging.carvel.dev/v1alpha1
          kind: PackageInstall
          metadata:
            name: pkg-install-carvel-helloworld
          spec:
            serviceAccountName: default-ns-sa
            packageRef:
              refName: example.bundle.com
              versionSelection:
                constraints: ">0.0.1"
          EOF

          export COSIGN_EXPERIMENTAL=1
          cosign sign-blob --output pkgr.sig pkgr.yaml 2>&1 | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' > pkgr.crt
          cosign sign-blob --output pkgi.sig pkgi.yaml 2>&1 | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' > pkgi.crt

      - name: Create Release
        run: |
          set -x
          assets=()
          for asset in ./pkgi.{yaml,sig,crt} ./pkgr.{yaml,sig,crt}; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}